var imgSrc=[
	{
		"line":[
			{"src":"img/Img1.jpg"}
		],
		"bgSrc":"./img/Img1Bg.jpg",
		"height":"250"
	},
	{
		"line":[
			{"src":"img/Img2_1.jpg"},
			{"src":"img/Img2_1.jpg"}
		],
		"bgSrc":"./img/Img2Bg.jpg",
		"height":"320"
	},
	{
		"line":[
			{"src":"img/Img3_1.jpg"},
			{"src":"img/Img3_2.jpg"}
		],
		"bgSrc":"./img/Img3Bg.jpg",
		"height":"318"
	},
	{
		"line":[
			{"src":"img/Img4_1.jpg"},
			{"src":"img/Img4_2.jpg"},
			{"src":"img/Img4_3.jpg"},
			{"src":"img/Img4_4.jpg"}
		],
		"bgSrc":"./img/Img4Bg.jpg",
		"height":"359"
	},
	{
		"line":[
			{"src":"img/Img5_1.jpg"},
			{"src":"img/Img5_2.jpg"},
			{"src":"img/Img5_3.jpg"},
			{"src":"img/Img5_4.jpg"}
		],
		"bgSrc":"./img/Img5Bg.jpg",
		"height":"350"
	},
	{
		"line":[
			{"src":"img/Img6_1.jpg"},
			{"src":"img/Img6_2.jpg"},
			{"src":"img/Img6_3.jpg"}
		],
		"bgSrc":"./img/Img6Bg.jpg",
		"height":"310"
	},
	{
		"line":[
			{"src":"img/Img7_1.jpg"},
			{"src":"img/Img7_2.jpg"},
			{"src":"img/Img7_3.jpg"},
			{"src":"img/Img7_4.jpg"}
		],
		"bgSrc":"./img/Img7Bg.jpg",
		"height":"320"
	},
	{
		"line":[
			{"src":"img/Img8_1.jpg"},
			{"src":"img/Img8_2.jpg"},
			{"src":"img/Img8_3.jpg"},
			{"src":"img/Img8_4.jpg"}
		],
		"bgSrc":"./img/Img8Bg.jpg",
		"height":"359"
	},
	{
		"line":[
			{"src":"img/Img9_1.jpg"}
		],
		"bgSrc":"./img/Img9Bg.jpg",
		"height":"259"
	},
	{
		"line":[
			{"src":"img/Img10_1.jpg"},
			{"src":"img/Img10_2.jpg"},
			{"src":"img/Img10_3.jpg"},
			{"src":"img/Img10_4.jpg"}
		],
		"bgSrc":"./img/Img10Bg.jpg",
		"height":"311"
	},
	{
		"line":[
			{"src":"img/Img11_1.jpg"}
		],
		"bgSrc":"./img/Img11Bg.jpg",
		"height":"262"
	},
	{
		"line":[
			{"src":"img/Img12_1.jpg"}
		],
		"bgSrc":"./img/Img12Bg.jpg",
		"height":"242"
	}
];
