var topNav_left=[{"titleLeft":"华为官网"},{"titleLeft":"荣耀官网"},{"titleLeft":"软件应用"},{"titleLeft":"花粉俱乐部"},{"titleLeft":"Select Region"}];
var topNav_right=[{"titleRight":[{"log":"登录"},{"log":"注册"}]},{"titleRight":"我的订单"},{"titleRight":"V码(优购码)"},{"titleRight":"手机版"},{"titleRight":"网站导航"}];
var appStore=[{"dropMenu_left":"软件应用"},{"dropMenu_left":"EMUI"},{"dropMenu_left":"应用市场"},{"dropMenu_left":"云服务"},{"dropMenu_left":"开发者联盟"}];
var webNav=[{"dropMenu_right":"网站导航"},{"dropMenu_right":"帮助中心"},{"dropMenu_right":"PC软件"},{"dropMenu_right":"数字音乐"},{"dropMenu_right":"爱旅"},{"dropMenu_right":"华为网盘"}];
var drop_logUl=[{"dropMenu_log":"我的订单","dropMenu_cart":""},{"dropMenu_log":"待支付","dropMenu_cart":""},{"dropMenu_log":"待评论","dropMenu_cart":""},{"dropMenu_log":"优惠券","dropMenu_cart":""},{"dropMenu_log":"站内信","dropMenu_cart":""}];
var iptsut=[{"iptSut":"荣耀8"},{"iptSut":"5A"},{"iptSut":"荣耀 NOTE 8"},{"iptSut":"P9"},{"iptSut":"畅玩5"}];
var dropCart=[{"dropCart_img":"img/drop_cart_img1.PNG","dropCart_text":"HUAWEI&ensp;G9&ensp;青春版&ensp;全网通版&ensp;16GB&ensp;ROM(白色)&ensp;原价￥1699，直降100元","dropCart_price":"1599","dropCart_count":"1"},{"dropCart_img":"img/drop_cart_img1.PNG","dropCart_text":"HUAWEI&ensp;G9&ensp;青春版&ensp;全网通版&ensp;16GB&ensp;ROM(白色)&ensp;原价￥1699，直降100元","dropCart_price":"1599","dropCart_count":"1"}];
var qrCode=[{"qrCode_src":"img/qrcode_vmall_app01.png","qrCode_text":"专享周三无线专场"},{"qrCode_src":"img/qrcode_vmall_wechat02.jpg","qrCode_text":"微信扫码关注我们"}];
var navLi=[{"title":"首页"},{"title":"荣耀专区"},{"title":"荣耀品牌日"},{"title":"荣耀8"},{"title":"HUAWEI&ensp;P9"},{"title":"智能家居"},{"title":"特惠配件"}]
var sideBarLi=[
{"title":"手机","titleInfo":[{"info":"荣耀"},{"info":"畅玩"},{"info":"华为&ensp;Mate/P系列"}],"detail":[{"info":"荣耀"},{"info":"畅玩"},{"info":"华为&ensp;Mate/P系列"},{"info":"华为&ensp;G系列"},{"info":"华为&ensp;畅享系列"},{"info":"运营商合约"}],"command":[{"info":"以旧换新"},{"info":"荣耀&ensp;NOTE8"},{"info":"华为&ensp;Mate&ensp;8"},{"info":"荣耀畅玩5X"}]},
{"title":"笔记本&平板","titleInfo":[{"info":"平板电脑"},{"info":"MateBook","icon":"true"},{"info":"扩展钨"}],"detail":[{"info":"平板电脑"},{"info":"MateBook","icon":"true"},{"info":"扩展钨"},{"info":"触控笔"},{"info":"二合一键盘"}],"command":[{"info":"荣耀平板"},{"info":"HUAWEI&ensp;WATCH"},{"info":"荣耀手环zero"}]},
{"title":"穿戴","titleInfo":[{"info":"手表"},{"info":"手环","icon":"true"}],"detail":[{"info":"手表"},{"info":"手环","icon":"true"}]},
{"title":"智能家居","titleInfo":[{"info":"子母路由"},{"info":"电视盒子"},{"info":"路由器"}],"detail":[{"info":"字母路由"},{"info":"电视盒子"},{"info":"路由器"},{"info":"电力猫"},{"info":"随行wifi"}],"command":[{"info":"荣耀路由Pro 游戏版"},{"info":"荣耀盒子Pro"},{"info":"荣耀路由"}]},
{"title":"专属配件","titleInfo":[{"info":"保护壳"},{"info":"保护套"},{"info":"贴膜"}],"detail":[{"info":"保护壳"},{"info":"保护套"},{"info":"贴膜"},{"info":"盒子专属配件"},{"info":"表带"},{"info":"电容笔"}],"command":[{"info":"荣耀 圈铁耳机"},{"info":"荣耀小口哨"},{"info":"耐翔 蜂巢 蓝牙耳机"}]},
{"title":"通用配件","titleInfo":[{"info":"耳机"},{"info":"音箱"},{"info":"移动电源"}],"detail":[{"info":"耳机"},{"info":"音箱"},{"info":"移动电源"},{"info":"自拍杆/支架"},{"info":"充电器/线材"},{"info":"U盘/储存卡"},{"info":"插排"},{"info":"摄像机/镜头"},{"info":"智能硬件","icon":"true"},{"info":"生活周边"}],"command":[{"info":"小天鹅蓝牙音箱"}]},
{"title":"应用市场","titleInfo":[{"info":"手机游戏"},{"info":"手机应用"}],"detail":[{"info":"手机应用"},{"info":"手机游戏"}]}];